/**
 * Marks generated markdown as generated, inside the file itself.
 *
 * Until this existed, the only signals that a file under `.claude/`, `.cursor/`,
 * `.github/instructions/` etc. was sync output were prose in the README and a
 * `.gitignore` entry. Neither travels with the file. A project that commits its
 * generated output (so `sync --check` can verify parity in CI) ends up with
 * generated and hand-authored markdown side by side, visually identical — and
 * the next editor, human or agent, silently loses their work on the next sync.
 *
 * The banner is emitted into the output only; sources under `llm/` never carry
 * one. {@link stripGeneratedBanner} runs first regardless, so a generated file
 * mistakenly copied back over its own source cannot stack banners — which makes
 * {@link withGeneratedBanner} idempotent.
 */

const BANNER_MARKER = 'Generated by bluetemberg';

export function generatedBanner(sourceId: string): string {
  return `<!-- ${BANNER_MARKER} from ${sourceId}. Do not edit — run \`bluetemberg sync\` after editing the source. -->`;
}

/**
 * Index just past the closing `---` delimiter of a leading YAML frontmatter
 * block, or `null` when the content does not open with one. Deliberately does
 * not parse the YAML: this only needs to know where the body starts.
 */
function frontmatterEnd(content: string): number | null {
  if (!content.startsWith('---\n')) return null;
  const close = content.indexOf('\n---\n', 3);
  if (close === -1) return null;
  return close + '\n---\n'.length;
}

/**
 * Removes a banner this module emitted, plus the single blank line it adds after
 * it, restoring the pre-banner text exactly.
 */
export function stripGeneratedBanner(content: string): string {
  const lines = content.split('\n');
  const index = lines.findIndex((line) => line.startsWith(`<!-- ${BANNER_MARKER}`));
  if (index === -1) return content;

  lines.splice(index, lines[index + 1] === '' ? 2 : 1);
  return lines.join('\n');
}

/** Inserts the banner after any frontmatter block, else at the top of the file. */
export function withGeneratedBanner(content: string, sourceId: string): string {
  const banner = generatedBanner(sourceId);
  const stripped = stripGeneratedBanner(content);

  const bodyStart = frontmatterEnd(stripped);
  if (bodyStart === null) {
    return `${banner}\n\n${stripped}`;
  }

  const frontmatter = stripped.slice(0, bodyStart);
  const body = stripped.slice(bodyStart).replace(/^\n+/, '');
  return `${frontmatter}\n${banner}\n\n${body}`;
}
