import { join, basename } from 'node:path';
import matter from 'gray-matter';
import { stringify as tomlStringify } from 'smol-toml';
import type { Platform } from '../types.js';
import { readIfExists } from '../utils/fs.js';
import type { SyncSink } from './pipeline.js';
import { commitPlannedWrite } from './pipeline.js';
import { mergeSourceFiles } from './extends-loader.js';
import { BUILTIN_MCP_SERVERS, parseLlmMcpServerList } from '../mcp/registry.js';
import type { McpServerConfig } from '../mcp/registry.js';
import { AGENTS_RULES_MARKERS, CODEX_MCP_MARKERS, injectManagedBlock } from './managed-block.js';

// Codex has no per-file rule API; see Architecture.md "Special sync" for the full design.
export interface CodexSyncContext extends SyncSink {
  sourceBase: string;
  sourceDirs: string[];
  platforms: readonly Platform[];
}

/** Stable filename ordering so generated output is deterministic across runs. */
function byFilename(a: [string, string], b: [string, string]): number {
  return a[0].localeCompare(b[0]);
}

/** Renders a scope annotation line, or empty for global (`**`) / unscoped rules. */
function scopeAnnotation(scope: string | string[] | undefined): string {
  if (scope === undefined) return '';
  const globs = Array.isArray(scope) ? scope : [scope];
  const meaningful = globs.filter((g) => g && g !== '**');
  if (meaningful.length === 0) return '';
  return `_Applies to: ${meaningful.map((g) => `\`${g}\``).join(', ')}_`;
}

/** Builds the inner body of the AGENTS.md rules block (empty when there are no rules). */
function buildRulesBlock(ctx: CodexSyncContext): string {
  const merged = mergeSourceFiles(ctx.sourceDirs, 'rules', (f) => f.endsWith('.md'));
  if (merged.size === 0) return '';

  const sections: string[] = [
    'Generated by bluetemberg from `llm/rules/`. Do not edit between the markers — run `bluetemberg sync`.',
  ];

  for (const [file, sourceDir] of [...merged].sort(byFilename)) {
    const parsed = matter.read(join(sourceDir, file));
    const scope = parsed.data.scope as string | string[] | undefined;
    sections.push([scopeAnnotation(scope), parsed.content.trim()].filter(Boolean).join('\n\n'));
  }

  return sections.join('\n\n');
}

function getSafeRulesBlock(ctx: CodexSyncContext, recordError: (message: string) => void): string | null {
  try {
    return buildRulesBlock(ctx);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    recordError(`codex rules -> AGENTS.md: ${message}`);
    return null;
  }
}

/**
 * Folds `llm/rules/` into a managed block in the root `AGENTS.md`, preserving hand-authored content.
 */
export function syncCodexRules(ctx: CodexSyncContext, recordError: (message: string) => void): void {
  if (!ctx.platforms.includes('codex')) return;

  const agentsPath = join(ctx.root, 'AGENTS.md');
  const existing = readIfExists(agentsPath);

  const block = getSafeRulesBlock(ctx, recordError);
  if (block === null) return;

  if (block.length === 0 && (existing === null || !existing.includes(AGENTS_RULES_MARKERS.begin))) {
    return;
  }

  const output = injectManagedBlock(existing, block, AGENTS_RULES_MARKERS);
  if (output.length === 0 && existing === null) return;

  commitPlannedWrite(ctx, agentsPath, output);
  if (!ctx.checkMode) ctx.log('Codex rules: merged into AGENTS.md');
}

function processAgentFile(
  file: string,
  sourceDir: string,
  outDir: string,
  ctx: CodexSyncContext,
  recordError: (message: string) => void,
): boolean {
  try {
    const parsed = matter.read(join(sourceDir, file));
    const fallbackName = basename(file, '.md');
    const name =
      typeof parsed.data.name === 'string' && parsed.data.name.trim().length > 0
        ? parsed.data.name.trim()
        : fallbackName;

    const agent: Record<string, unknown> = {
      name,
      description: typeof parsed.data.description === 'string' ? parsed.data.description : '',
      developer_instructions: parsed.content.trim(),
    };

    const body = tomlStringify(agent) + '\n';
    commitPlannedWrite(ctx, join(outDir, `${fallbackName}.toml`), body);
    return true;
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    recordError(`codex agent ${file}: ${message}`);
    return false;
  }
}

/** Emits one `.codex/agents/<name>.toml` per source agent, mapping the body to `developer_instructions`. */
export function syncCodexAgents(ctx: CodexSyncContext, recordError: (message: string) => void): void {
  if (!ctx.platforms.includes('codex')) return;

  const merged = mergeSourceFiles(ctx.sourceDirs, 'agents', (f) => f.endsWith('.md') && f !== 'README.md');
  if (merged.size === 0) return;

  const outDir = join(ctx.root, '.codex', 'agents');

  const count = [...merged]
    .sort(byFilename)
    .filter(([file, sourceDir]) => processAgentFile(file, sourceDir, outDir, ctx, recordError)).length;

  if (count > 0 && !ctx.checkMode) ctx.log(`Codex agents: ${count} -> .codex/agents/`);
}

/** Reads `llm/mcp.json` into resolved server configs, surfacing parse errors via `recordError`. */
function readMcpConfigs(
  sourceBase: string,
  recordError: (message: string) => void,
): Record<string, McpServerConfig> {
  const raw = readIfExists(join(sourceBase, 'mcp.json'));
  if (raw === null) return {};

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    recordError(`codex mcp: failed to parse llm/mcp.json: ${message}`);
    return {};
  }

  const servers =
    parsed && typeof parsed === 'object' && !Array.isArray(parsed)
      ? (parsed as Record<string, unknown>).servers
      : undefined;
  if (!Array.isArray(servers)) return {};

  const { configs } = parseLlmMcpServerList(servers, BUILTIN_MCP_SERVERS);
  return configs;
}

/** Maps our internal MCP shape to Codex's TOML shape (stdio = command/args, HTTP = url). */
function toCodexMcpServers(
  configs: Record<string, McpServerConfig>,
): Record<string, Record<string, unknown>> {
  const out: Record<string, Record<string, unknown>> = {};
  for (const [id, cfg] of Object.entries(configs)) {
    const entry: Record<string, unknown> = {};
    if (cfg.url) {
      entry.url = cfg.url;
    } else if (cfg.command) {
      entry.command = cfg.command;
      if (cfg.args && cfg.args.length > 0) entry.args = cfg.args;
    }
    // Skip entries with no transport — neither url nor command were set.
    if (Object.keys(entry).length > 0) out[id] = entry;
  }
  return out;
}

function buildMcpInner(sourceBase: string, recordError: (message: string) => void): string | null {
  try {
    const servers = toCodexMcpServers(readMcpConfigs(sourceBase, recordError));
    return Object.keys(servers).length > 0 ? tomlStringify({ mcp_servers: servers }).trim() : '';
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    recordError(`codex mcp -> .codex/config.toml: ${message}`);
    return null;
  }
}

/** Injects a managed `[mcp_servers.*]` block into `.codex/config.toml`, preserving hand-authored config. */
export function syncCodexConfig(ctx: CodexSyncContext, recordError: (message: string) => void): void {
  if (!ctx.platforms.includes('codex')) return;

  const configPath = join(ctx.root, '.codex', 'config.toml');
  const existing = readIfExists(configPath);

  const inner = buildMcpInner(ctx.sourceBase, recordError);
  if (inner === null) return;

  if (inner.length === 0 && (existing === null || !existing.includes(CODEX_MCP_MARKERS.begin))) {
    return;
  }

  const output = injectManagedBlock(existing, inner, CODEX_MCP_MARKERS);
  if (output.length === 0 && existing === null) return;

  commitPlannedWrite(ctx, configPath, output);
  if (!ctx.checkMode) ctx.log('Codex MCP: merged into .codex/config.toml');
}
