import { describe, it, expect } from 'vitest';
import { generatedBanner, stripGeneratedBanner, withGeneratedBanner } from '../src/sync/banner.js';

const SOURCE = 'rules/no-console-log.md';

describe('withGeneratedBanner', () => {
  it('inserts the banner after a frontmatter block, before the body', () => {
    const content = '---\ndescription: No console\nscope: "src/**"\n---\n\n# No console\n\nBody text.\n';

    expect(withGeneratedBanner(content, SOURCE)).toBe(
      '---\ndescription: No console\nscope: "src/**"\n---\n\n' +
        `${generatedBanner(SOURCE)}\n\n` +
        '# No console\n\nBody text.\n',
    );
  });

  it('inserts the banner at the top when there is no frontmatter', () => {
    const content = '# Just a heading\n\nBody.\n';

    expect(withGeneratedBanner(content, SOURCE)).toBe(
      `${generatedBanner(SOURCE)}\n\n# Just a heading\n\nBody.\n`,
    );
  });

  it('names the source it was generated from', () => {
    expect(withGeneratedBanner('# x\n', 'skills/my-skill/SKILL.md')).toContain(
      'from skills/my-skill/SKILL.md',
    );
  });

  it('is idempotent — re-running sync never stacks banners', () => {
    const content = '---\nname: agent\n---\n\n# Agent\n';
    const once = withGeneratedBanner(content, SOURCE);
    const twice = withGeneratedBanner(once, SOURCE);

    expect(twice).toBe(once);
    expect(twice.match(/Generated by bluetemberg/g)).toHaveLength(1);
  });

  it('replaces a stale banner rather than appending a second one', () => {
    const stale = withGeneratedBanner('---\nname: agent\n---\n\n# Agent\n', 'agents/old-name.md');
    const fresh = withGeneratedBanner(stale, 'agents/new-name.md');

    expect(fresh).toContain('from agents/new-name.md');
    expect(fresh).not.toContain('from agents/old-name.md');
    expect(fresh.match(/Generated by bluetemberg/g)).toHaveLength(1);
  });

  it('leaves body content untouched, including --- separators inside the body', () => {
    const content = '---\nname: x\n---\n\n# Title\n\n---\n\nAfter a horizontal rule.\n';

    expect(withGeneratedBanner(content, SOURCE)).toContain('# Title\n\n---\n\nAfter a horizontal rule.\n');
  });

  it('treats an unterminated frontmatter fence as no frontmatter', () => {
    const content = '---\nname: never closed\n';

    expect(withGeneratedBanner(content, SOURCE)).toBe(`${generatedBanner(SOURCE)}\n\n${content}`);
  });
});

describe('stripGeneratedBanner', () => {
  it('restores the exact pre-banner content', () => {
    const content = '---\nname: agent\n---\n\n# Agent\n';

    expect(stripGeneratedBanner(withGeneratedBanner(content, SOURCE))).toBe(content);
  });

  it('is a no-op on content that has no banner', () => {
    const content = '# Nothing generated here\n';

    expect(stripGeneratedBanner(content)).toBe(content);
  });
});
